apiVersion: v1
kind: Service
metadata:
  name: meeting-server-service
  namespace: learn-istio
  labels:
     componet: meeting-server
spec:
  selector:
    component: meeting-server
  ports:
   - protocol: 'TCP'
     port: 8081
     targetPort: 8081
  type: ClusterIP
