apiVersion: v1
kind: Service
metadata:
  name: work-server-service
  namespace: learn-istio
  labels:
          componet: work-server
spec:
  selector:
    component: work-server
  ports:
   - protocol: 'TCP'
     port: 8080
     targetPort: 8080
  type: ClusterIP
